CREATE TABLE IF NOT EXISTS `sys_script` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`appname` CHAR(100) NOT NULL DEFAULT '',
	`remark` CHAR(200) NOT NULL DEFAULT '',
	`plan_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
	`script` varchar(10000) NOT NULL DEFAULT '',
	`verify` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
);


CREATE TABLE IF NOT EXISTS `sys_app` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`appname` CHAR(100) NOT NULL DEFAULT '',
	`remark` CHAR(200) NOT NULL DEFAULT '',
	`secret` CHAR(100) NOT NULL DEFAULT '',
	`verify` TINYINT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UNIQUE `appname_index` (`appname`) USING BTREE,
	PRIMARY KEY (`id`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `sys_user_0`(
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`userid` CHAR(100) NOT NULL DEFAULT '',
	`attribute` varchar(10000) NOT NULL DEFAULT '',
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE `userid_index` (`userid`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `sys_table_ddl` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`appname` CHAR(100) NOT NULL DEFAULT '',
	`remark` CHAR(200) NOT NULL DEFAULT '',
	`ddl` varchar(10000) NOT NULL DEFAULT '',
	`exec_outin` varchar(1000) NOT NULL DEFAULT '',
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
);
